version: '3.8'

services:
  discord-exporter:
    image: tyrrrz/discordchatexporter
    container_name: discord-exporter
    volumes:
      - ./exports:/out
    environment:
      - TZ=${EXPORT_TIMEZONE:-Europe/Paris}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    env_file:
      - .env
    # Le conteneur ne démarre pas automatiquement car il nécessite des commandes spécifiques
    # pour l'export. Il sera utilisé via docker-compose run
    command: tail -f /dev/null 